name = "Mediumcore"
author = "purplepentagons"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd93ac4af3743f81799e4e66534be6397ca784b679c2d5a508c30dab9abdb4d3"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"

[options]
meta-folder = "links/"
