name = "Mediumcore"
author = "purplepentagons"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7b4182de6bda895921cf930bd81393e8fff0fed7a08c7277b0170d8f44e1432"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"

[options]
meta-folder = "links/"
